name: resparify5
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  flutter_svg: ^2.0.9
  youtube_player_flutter: ^8.1.2
  validatorless: ^1.2.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.15.3
  provider: ^6.1.1
  image_picker: ^1.0.6
  model_viewer_plus: ^1.7.0
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/3d_model/
    - assets/images/

  fonts:
    - family: AveriaSerifLibre
      fonts:
        - asset: assets/fonts/AveriaSerifLibre-Light.ttf
          weight: 300
        - asset: assets/fonts/AveriaSerifLibre-Regular.ttf
          weight: 400
        - asset: assets/fonts/AveriaSerifLibre-Bold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
